// exporting const TYPES object
export const TYPES = {
    'SHOW_LOADER': 'SHOW_LOADER',
    'CLEAR_LOADER': 'CLEAR_LOADER',
    'FETCH_POPULAR_MOVIES': 'FETCH_POPULAR_MOVIES',
    'FETCH_POPULAR_MOVIES_LOADING': 'FETCH_POPULAR_MOVIES_LOADING',
    'FETCH_POPULAR_MOVIES_FINISHED': 'FETCH_POPULAR_MOVIES_FINISHED',
    'FETCH_GENRES': 'FETCH_GENRES',
    'FETCH_GENRES_LOADING': 'FETCH_GENRES_LOADING',
    'FETCH_GENRES_FINISHED': 'FETCH_GENRES_FINISHED',
    'SET_SELECTED_MENU_OPTIONS': 'SET_SELECTED_MENU_OPTIONS',
    'CLEAR_SELECTED_MENU_OPTIONS': 'CLEAR_SELECTED_MENU_OPTIONS',
    'SET_ERROR': 'SET_ERROR',
    'CLEAR_ERROR': 'CLEAR_ERROR',
    'FETCH_MOVIES_RECOMMENDATIONS': 'FETCH_MOVIES_RECOMMENDATIONS',
    'FETCH_MOVIES_RECOMMENDATIONS_LOADING': 'FETCH_MOVIES_RECOMMENDATIONS_LOADING',
    'FETCH_MOVIES_RECOMMENDATIONS_FINISHED': 'FETCH_MOVIES_RECOMMENDATIONS_FINISHED',
    'SHOW_VIDEO_MODAL': 'SHOW_VIDEO_MODAL',
    'CLEAR_VIDEO_MODAL': 'CLEAR_VIDEO_MODAL'
};