
export const SHOW_LOADER = 'SHOW_LOADER';
export const CLEAR_LOADER = 'CLEAR_LOADER';
export const FETCH_POPULAR_MOVIES = 'FETCH_POPULAR_MOVIES';
export const FETCH_POPULAR_MOVIES_LOADING = 'FETCH_POPULAR_MOVIES_LOADING';
export const FETCH_POPULAR_MOVIES_FINISHED = 'FETCH_POPULAR_MOVIES_FINISHED';
export const FETCH_GENRES = 'FETCH_GENRES';
export const FETCH_GENRES_LOADING = 'FETCH_GENRES_LOADING';
export const FETCH_GENRES_FINISHED = 'FETCH_GENRES_FINISHED';
export const SET_SELECTED_MENU_OPTIONS = 'SET_SELECTED_MENU_OPTIONS';
export const CLEAR_SELECTED_MENU_OPTIONS = 'CLEAR_SELECTED_MENU_OPTIONS';
export const SET_ERROR = 'SET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const FETCH_MOVIES_RECOMMENDATIONS = 'FETCH_MOVIES_RECOMMENDATIONS';
export const FETCH_MOVIES_RECOMMENDATIONS_LOADING = 'FETCH_MOVIES_RECOMMENDATIONS_LOADING';
export const FETCH_MOVIES_RECOMMENDATIONS_FINISHED = 'FETCH_MOVIES_RECOMMENDATIONS_FINISHED';
export const SHOW_VIDEO_MODAL = 'SHOW_VIDEO_MODAL';
export const CLEAR_VIDEO_MODAL = 'CLEAR_VIDEO_MODAL';
